version: "3.8"

services:
  drive-health:
    # Latest image pull, mention the specific version here please.
    image: ghcr.io/justkato/drive-health:latest
    # Restart in case of crashing
    restart: unless-stopped
    # Load environment variables from .env file
    env_file:
      - .env
    # Mount the volume to the local drive
    volumes:
      - ./data:/data
    # Setup application ports
    ports:
      - 5003:8080